name: "Terraform Actions"
description: "Running Terraform commands (fmt, init, plan, apply, validate)"

inputs:
  arg:
    description: "Arguments to be used with Terraform"
    required: true
  github-token:
    description: "GitHub token for posting comments"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.arg }}
    - ${{ secrets.GITHUB_TOKEN }}
