name: Test Terraform PR Commenter

on: [pull_request]

jobs:
  terraform-comment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Terraform PR Commenter
      uses: andresb39/terraform-pr-commenter@tf0.11.15
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}