name: Test Terraform PR Commenter

on: [pull_request]

jobs:
  terraform-comment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update PR comment
      uses: andresb39/terraform-pr-commenter@tf1.4.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
