name: Test Terraform PR Commenter

on: [pull_request]

jobs:
  terraform-comment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update PR comment
      uses: myCloudDoor-Corporate/myCD-tf-deploy/@v1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
